name: Inga Analysis

on:
  pull_request:

jobs:
  inga-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # https://github.com/actions/checkout/issues/124
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: seachicken/inga-action@main
      with:
        language: "java"
        exclude: "src/test/**"
