name: Inga Analysis

on:
  pull_request:

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: inga-report
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # https://github.com/actions/checkout/issues/124
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: seachicken/inga-action@main
      with:
        language: "java"
        exclude: "src/test/**"
    - uses: actions/upload-pages-artifact@v3
      with:
        name: inga-report
        path: inga-report/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: inga-report
