name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Set version
      run: |
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Publish Plugin to JetBrains Marketplace
      if: "!contains(github.ref_name, 'SNAPSHOT')"
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: |
        ./gradlew publishPlugin -PpluginVersion=$VERSION -Pchannel=default
    - name: Upload to GitHub Releases
      if: "!contains(github.ref_name, 'SNAPSHOT')"
      run: gh release create --title ${{ github.ref_name }} --generate-notes ${{ github.ref_name }} ./build/distributions/*

    - name: Publish Plugin to JetBrains Marketplace for BETA
      if: "contains(github.ref_name, 'SNAPSHOT')"
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: |
        ./gradlew publishPlugin -PpluginVersion=$VERSION -Pchannel=beta
    - name: Upload to GitHub Releases for BETA
      if: "contains(github.ref_name, 'SNAPSHOT')"
      run: gh release create --title ${{ github.ref_name }} --generate-notes --draft ${{ github.ref_name }} ./build/distributions/*